spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=auth
    username: ecommerce
    password: secret
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    drop-first: false

app:
  jwt:
    secret: dev-secret-change-me-please-at-least-32chars-long-123

logging:
  level:
    com.ecommerce.auth: DEBUG
